# 소프트맥스 오버플로우 방지

In [9]:
import numpy as np

def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)

def stable_softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x)

x = np.array([1000, 1001, 1002])

print(softmax(x))
print(stable_softmax(x))

[nan nan nan]
[0.09003057 0.24472847 0.66524096]


/var/folders/kp/5_0zhw410tzf9tkb2lt76sw40000gn/T/ipykernel_4617/300004869.py:4: RuntimeWarning: overflow encountered in exp
  exp_x = np.exp(x)
/var/folders/kp/5_0zhw410tzf9tkb2lt76sw40000gn/T/ipykernel_4617/300004869.py:5: RuntimeWarning: invalid value encountered in divide
  return exp_x / np.sum(exp_x)


- pytouch 라이브러리 함수 사용

In [14]:
import torch
import torch.nn.functional as F

x = torch.tensor([2.0, 1.0, 0.1], dtype=torch.float32)

softmax_output = F.softmax(x, dim=0)    # dim: softmax를 적용할 축
print(softmax_output)

sigmoid_output = torch.sigmoid(x)
print(sigmoid_output)

tensor([0.6590, 0.2424, 0.0986])
tensor([0.8808, 0.7311, 0.5250])


In [2]:
import torch
import torch.nn as nn
import torch.optim as optim

# 간단한 다중 클래스 분류 모델 정의 (입력 값: 5개, 출력: 3 클래스)
class SimpleMultiClassModel(nn.Module):
    def __init__(self):
        super(SimpleMultiClassModel, self).__init__()
        self.fc = nn.Linear(5, 3)

    def forward(self, x):
        return self.fc(x)

model = SimpleMultiClassModel()
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# 데이터 생성
inputs = torch.randn(4, 5)
labels = torch.tensor([0, 2, 1, 0])

for _ in range(10):
    outputs = model(inputs) # 순전파
    loss = criterion(outputs, labels)   # 손실 계산
    print(loss.item())

    optimizer.zero_grad()   # 이전 단계에서 계산된 기울기를 0으로 초기화
    loss.backward()         # 손실에 대한 역전파 수행 (파라미터에 대한 기울기 계산)
    optimizer.step()        # 계산된 기울기를 사용하여 옵티마이저가 모델의 파라미터 업데이트



1.5731444358825684
1.54547917842865
1.5180859565734863
1.490976095199585
1.464160442352295
1.4376498460769653
1.411454439163208
1.385584831237793
1.360050916671753
1.334862232208252
