# nparray의 기본 연산

In [2]:
import numpy as np

In [7]:
# 2차원 배열 연산
arr_a = np.arange(1, 10).reshape(3, 3) # .reshape() N차원의 모습으로 만들어 줌
arr_b = np.full_like(arr_a, 3) # .full_like(변수, 특정값) 차원이 있는 '변수'와 같은 모양으로 '특정값'으로 요소를 채워줌

print(arr_a)
print(arr_b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [6]:
# 덧셈
print(arr_a + arr_b) 
print(np.add(arr_a, arr_b))
      

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
# 뺄셈
print(arr_a - arr_b) #
print(np.subtract(arr_a, arr_b))

[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]
[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]


In [8]:
# 곱셈
print(arr_a * arr_b) #
print(np.multiply(arr_a, arr_b))

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [9]:
# 나눗셈
print(arr_a / arr_b) #
print(np.divide(arr_a, arr_b))

[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]
[[0.33333333 0.66666667 1.        ]
 [1.33333333 1.66666667 2.        ]
 [2.33333333 2.66666667 3.        ]]


In [ ]:
# 특수연산 1: 거듭제곱
print(arr_a ** arr_b) #
print(np.power(arr_a, arr_b))
print

In [11]:
# 특수연산 2: 몫
print(arr_a // arr_b) #
print(np.floor_divide(arr_a, arr_b)) #

[[0 0 1]
 [1 1 2]
 [2 2 3]]
[[0 0 1]
 [1 1 2]
 [2 2 3]]


In [12]:
# 특수연산 3: 나머지
print(arr_a % arr_b) #
print(np.mod(arr_a, arr_b))

[[1 2 0]
 [1 2 0]
 [1 2 0]]
[[1 2 0]
 [1 2 0]
 [1 2 0]]


In [13]:
# 제곱근
print(np.sqrt(arr_a))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [21]:
# p1
sales1 = [200, 340, 150, 400] 
sales2 = [220, 300, 180, 420]

sum = np.add(sales1, sales2)
# avg = np.add(sales1, sales2) / 2
avg = np.divide(np.add(sales1, sales2), 2)

print(sum)
print(avg)

[420 640 330 820]
[210. 320. 165. 410.]


In [19]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

print(np.add(arr1, arr2))
print(np.subtract(arr1, arr2))
print(np.multiply(arr1, arr2))
print(np.divide(arr1,arr2))

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]


---

### broadcasting 연산
- 두 배열의 shape이 다르면 broadcasting 연산을 수행한다.
- shape이 작은 쪽이 큰 쪽에 맞춰 확장한다.
- 두 배열의 행 또는 열이 일치해야 확장 가능하다.
- 크기가 1인 경우 무조건 확장 가능하다.
- shape이 다른 경우 마지막 축부터 차원이 동일한지 비교한다.

In [10]:
result_arr = arr_a * np.array([[5, 5, 5], [5, 5, 5], [5, 5, 5]]) # (3, 3)
result_arr = arr_a * np.array([5, 5, 5]) # (3,)
result_arr = arr_a * np.array([5]) # (3,)
result_arr = arr_a * 5 # (3,)
result_arr 

array([[ 5,  8,  9],
       [20, 20, 18],
       [35, 32, 27]])

In [12]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
arr2 = np.array([5, 10, 100])           # (3,)

arr1 + arr2

array([[  6,  12, 103],
       [  9,  15, 106]])

In [13]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
arr2 = np.array([[100], [200]])
arr1 + arr2

array([[101, 102, 103],
       [204, 205, 206]])

In [15]:
arr1 = np.array([1, 2, 3]) #(3,)
arr2 = np.array([[4], [5], [6]]) #(3, 1)
arr1.shape, arr2.shape
arr1 + arr2

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [ ]:
# 크기가 작은 쪽이 큰 쪽을 따라간다

arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
arr2 = np.array([1, 2])                 # (2,)
# arr1 + arr2   # Values error



---
### 행렬 곱셈
- 점곱연산 (Dot Product / 내적)
    - 두 행렬 A, B의 곱셈은 첫 번째 행렬 A의 행과 두 번째 행렬 B의 열 간의 곱셈을 수행한다.
    - 첫 번째 행렬 A의 열의 수와 두 번째 행렬 B의 행의 수가 같아야 한다.
    - 연산 결과의 shape은 (첫 번째 행렬 A의 행수, 두 번째 행렬 B의 열수)이다.

In [4]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1 * arr2)
print(arr1.shape,arr2.shape, (arr1*arr2).shape)

print(np.dot(arr1,arr2))
print(np.dot(arr1,arr2).shape)

[[ 5 12]
 [21 32]]
(2, 2) (2, 2) (2, 2)
[[19 22]
 [43 50]]
(2, 2)


In [6]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[7, 8], [9, 10], [11, 12]])
print(arr3.shape, arr4.shape, np.dot(arr3, arr4).shape)
# np.dot(arr3, arr4).shape -> (2,3) * (3,2) = (2,2)
# np.dot(arr4, arr3).shape -> (3,2) * (2,3) = (3,3)

(2, 3) (3, 2) (2, 2)


In [ ]:
# (100, 100)
# (20000, 20000)
# Valueserror

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# @
# print(arr @ arr)

# .T    전치 행렬
print(arr)
print(arr.T)
print(arr @ arr.T)

print(np.matmul(arr, arr.T))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]
[[14 32]
 [32 77]]


In [11]:
# 3
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.array([10, 20, 30])

print(arr1d + arr2d)

[[11 22 33]
 [14 25 36]]


### 연산 함수 및 집계 함수

In [18]:
arr_negative = np.array([[-1, -2], [-100, -200]])
arr_float = np.array([[1.234, 5.678], [7.89, 10.123]])                        

In [14]:
# 절댓값
np.abs(arr_negative)

array([[  1,   2],
       [100, 200]])

In [21]:
# 올림/반올림
print(np.ceil(arr_float))
print(np.round(arr_float))
print(np.round(arr_float, 2))

[[ 2.  6.]
 [ 8. 11.]]
[[ 1.  6.]
 [ 8. 10.]]
[[ 1.23  5.68]
 [ 7.89 10.12]]


In [22]:
arr_float = np.array([[1.234, 5.678], [7.89, 10.123]])

# 내림
print(np.floor(arr_float))
# 버림
print(np.trunc(arr_float))

[[ 1.  5.]
 [ 7. 10.]]
[[ 1.  5.]
 [ 7. 10.]]


In [26]:
# 최대값/최소값
print(np.max(arr))
print(np.min(arr))

print(np.max(arr, axis=0))  # 행 기준 (행을 고정하고, 같은 열에서 가장 큰 값)
print(np.min(arr, axis=1))  # 열 기준 (열을 고정하고, 같은 행에서 가장 작은 값)


6
1
[4 5 6]
[1 4]


In [28]:
# 합계  
print(arr.sum())    # axis=None
print(np.sum(arr))  

print(arr.sum(axis=0))    # axis=0 행 기준 (행 방향 덧셈)
print(arr.sum(axis=1))    # axis=1 열 기준 (열 방향 덧셈)

21
21
[5 7 9]
[ 6 15]


In [29]:
# 평균
print(arr.mean())
print(np.mean(arr))

print(arr.mean(axis=0))
print(arr.mean(axis=1))

3.5
3.5
[2.5 3.5 4.5]
[2. 5.]


In [33]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[arr>20])
print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))

[30 40 50]
150
50
10
30.0
