## ndarray 정렬

In [2]:
import numpy as np

### 1차원 배열 정렬

In [3]:
arr = np.random.randint(1, 11, 10)
arr

array([1, 5, 2, 3, 8, 6, 2, 2, 5, 6])

In [5]:
arr = np.sort(arr)
print(arr)

[1 2 2 2 3 5 5 6 6 8]


In [ ]:
np.sort(arr)

### 2차원 배열 정렬

In [8]:
arr = np.random.randint(10, size=(3, 4))  # 0 이상 10 미만
arr

array([[6, 2, 0, 2],
       [4, 2, 2, 2],
       [9, 1, 5, 6]])

In [9]:
print(np.sort(arr, axis=0)) # 행 방향 정렬
print(np.sort(arr, axis=1)) # 열 방향 정렬

[[4 1 0 2]
 [6 2 2 2]
 [9 2 5 6]]
[[0 2 2 6]
 [2 2 2 4]
 [1 5 6 9]]


In [10]:
print(np.sort(arr, axis=None))      # axis=None 축 무시 (행/열 구분없이 모든 값 정렬)
print(np.sort(arr, axis=None).shape)

[0 1 2 2 2 2 2 4 5 6 6 9]
(12,)


- np.argsort()
    - 배열의 값을 정렬했을 때, 각 값의 원래 인덱스를 반환
    - 정렬할 때 어떤 순서로 값을 배치해야 하는지 알려주는 인덱스를 반환
    - 배열의 값을 정렬한 후, 정렬된 순서에 해당하는 인덱스를 반환

In [12]:
arr = np.array([100, 400, 200, 300])
print(np.sort(arr))
print(np.argsort(arr))

[100 200 300 400]
[0 2 3 1]


In [23]:
names = np.array(['리사', '로제', '제니', '지수'])
album_sales = np.array([900, 870, 1000, 670])
print(np.argsort(album_sales)[::-1])

sales_desc = np.argsort(album_sales)[::-1]
names[sales_desc]

[2 0 1 3]


array(['제니', '리사', '로제', '지수'], dtype='<U2')

In [25]:
# 2차원 배열에서 argsort
arr = np.array([[2025, 1, 10], [15, 40, 30]])

print(np.argsort(arr))
print(np.argsort(arr, axis=1))
print(np.argsort(arr, axis=0))

[[1 2 0]
 [0 2 1]]
[[1 2 0]
 [0 2 1]]
[[1 0 0]
 [0 1 1]]


In [32]:
# 1
arr = np.array([50, 10, 30, 40, 20])
print(np.sort(arr))
print(np.sort(arr)[::-1])

# 2
arr2d = np.array([[8, 3, 5], [2, 9, 1]])
print(np.sort(arr2d, axis=0))
print(np.sort(arr2d, axis=1))

# 3
arr = np.array([15, 10, 20])
print(np.argsort(arr))

[10 20 30 40 50]
[50 40 30 20 10]
[[2 3 1]
 [8 9 5]]
[[3 5 8]
 [1 2 9]]
[1 0 2]
