### ndarray 형태 변경

In [5]:
import numpy as np

In [22]:
# reshape()
arr = np.arange(12)
print(arr.ndim, arr)

arr = arr.reshape(3, 4)
arr = arr.reshape(6, 2)
arr = arr.reshape(1,12)
# arr = arr.reshape(2, 7)
print(arr.ndim, arr.shape)
print(arr)

arr = arr.reshape(2, 2, 3)
# arr = arr.reshape(2, 2, 2)
print(arr.ndim, arr.shape)
print(arr)

1 [ 0  1  2  3  4  5  6  7  8  9 10 11]
2 (1, 12)
[[ 0  1  2  3  4  5  6  7  8  9 10 11]]
3 (2, 2, 3)
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [19]:
# reshape() -> -1
arr = arr.reshape(-1)
print(arr)

arr = arr.reshape(4, -1)
arr = arr.reshape(-1, 4)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [24]:
# np.ravel()
arr = np.arange(50).reshape(5, 10)
print(arr)
print(np.ravel(arr))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [39]:
# np.expand_dims()
arr_1d = np.arange(10)
print(arr_1d.shape, arr_1d)

print(np.expand_dims(arr_1d, axis=0))
print(np.expand_dims(arr_1d, axis=0).shape)
print(np.expand_dims(arr_1d, axis=1))
print(np.expand_dims(arr_1d, axis=1).shape)

(10,) [0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


In [34]:
arr_2d = np.array([[1, 2], [3, 4]])     
print(arr_2d.shape, arr_2d)     

print(np.expand_dims(arr_2d, axis=0))
print(np.expand_dims(arr_2d, axis=0).shape)
print(np.expand_dims(arr_2d, axis=1))
print(np.expand_dims(arr_2d, axis=1).shape)
print(np.expand_dims(arr_2d, axis=2))
print(np.expand_dims(arr_2d, axis=2).shape)

(2, 2) [[1 2]
 [3 4]]
[[[1 2]
  [3 4]]]
(1, 2, 2)
[[[1 2]]

 [[3 4]]]
(2, 1, 2)
[[[1]
  [2]]

 [[3]
  [4]]]
(2, 2, 1)


In [38]:
# np.squeeze() : 차원의 값이 1일 때 제거
arr = np.array([[1, 2]])
print(arr.shape)

arr2 =  np.squeeze(arr)
arr2 =  np.squeeze(arr, axis=0)
# arr2 =  np.squeeze(arr, axis=1)
print(arr2.shape)

(1, 2)
(2,)


In [46]:
# 1
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(np.concatenate((arr1, arr2)))
print(np.hstack([arr1, arr2]))

# 2
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(np.concatenate((arr1, arr2)))
print(np.vstack([arr1, arr2]))


[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [95]:
# 종합 실습
import numpy as np


# 5개 지점의 월별 사과, 바나나, 오렌지 판매량 (5x3x6 배열)
# 5개의 지점, 3개의 과일(사과, 바나나, 오렌지), 6개월치 데이터
sales_data = np.array([
    # 지점 1
    [[120, 150, 200, 230, 180, 210],  # 사과 판매량
     [100, 140, 170, 190, 160, 180],  # 바나나 판매량
     [90, 120, 160, 140, 130, 150]],  # 오렌지 판매량

    # 지점 2
    [[80, 90, 110, 140, 130, 120],
     [60, 70, 90, 100, 110, 95],
     [50, 80, 100, 110, 90, 85]],

    # 지점 3
    [[130, 140, 160, 180, 170, 190],
     [110, 120, 130, 150, 140, 160],
     [100, 110, 120, 130, 120, 140]],

    # 지점 4
    [[100, 130, 150, 170, 160, 180],
     [90, 100, 110, 120, 130, 125],
     [80, 110, 140, 130, 120, 110]],

    # 지점 5
    [[90, 110, 130, 140, 120, 130],
     [70, 85, 100, 110, 105, 95],
     [60, 90, 110, 100, 90, 95]]
])


[[181.66666667 156.66666667 131.66666667]
 [111.66666667  87.5         85.83333333]
 [161.66666667 135.         120.        ]
 [148.33333333 112.5        115.        ]
 [120.          94.16666667  90.83333333]]


[[520 620 750 860 760 830]
 [430 515 600 670 645 655]
 [380 510 630 610 550 580]]
[520 620 750 860 760 830]
[0 0 0 0 0 0]
[230 190 160]
1번 과일입니다.


[200 230 180 210 170 190 160 180 160 160 180 170 190 160 170 160 180]
120
0지점 1번 과일은 150개 입니다.
0지점 1번 과일은 200개 입니다.
0지점 1번 과일은 230개 입니다.
0지점 1번 과일은 180개 입니다.
0지점 1번 과일은 210개 입니다.
0지점 2번 과일은 170개 입니다.
0지점 2번 과일은 190개 입니다.
0지점 2번 과일은 160개 입니다.
0지점 2번 과일은 180개 입니다.
0지점 3번 과일은 160개 입니다.
0지점 3번 과일은 150개 입니다.
2지점 1번 과일은 160개 입니다.
2지점 1번 과일은 180개 입니다.
2지점 1번 과일은 170개 입니다.
2지점 1번 과일은 190개 입니다.
2지점 2번 과일은 150개 입니다.
2지점 2번 과일은 160개 입니다.
3지점 1번 과일은 150개 입니다.
3지점 1번 과일은 170개 입니다.
3지점 1번 과일은 160개 입니다.
3지점 1번 과일은 180개 입니다.


In [ ]:
#1. 각 지점에서 6개월 동안 판매된 **사과**, **바나나**, **오렌지**의 월별 평균 판매량을 계산하세요.
print(np.mean(sales_data, axis=2))
print('\n')


In [96]:
#2. 각 월마다 전체 지점에서 가장 많이 판매된 과일을 찾아 판매량과 과일명을 출력하세요.
# month_fruit = np.max(sales_data, axis=0)
# print(month_fruit)
# month_best = np.max(month_fruit, axis=0)
# print(month_best)
# for i in range(6):
#     for j in range(3):
#         if month_best[i] == month_fruit[j][i]:
#             print(f"{i+1}월: {j+1}번 과일입니다.")
# print('\n')

# T
total_sales_per_month = np.sum(sales_data, axis=0)
max_sales_per_month = np.max(total_sales_per_month, axis=0)
max_sales_indices = np.argmax(total_sales_per_month, axis=0)

print(total_sales_per_month)
print(max_sales_per_month)
print(max_sales_indices)

[[520 620 750 860 760 830]
 [430 515 600 670 645 655]
 [380 510 630 610 550 580]]
[520 620 750 860 760 830]
[0 0 0 0 0 0]


In [107]:
#3. 6개월 동안 전체 지점에서 가장 많이 판매된 과일의 총량을 과일별로 구하세요. 어떤 과일이 가장 많이 판매되었는지 확인하세요.
sales_datas = np.hstack([sales_data[0], sales_data[1], sales_data[2], sales_data[3], sales_data[4]])
best_fruits = np.sum(sales_datas, axis=1)
print(best_fruits)
print(np.argmax(best_fruits))

# T
total_sales_per_fruit = np.sum(sales_data, axis=(0, 2))     # axis를 한 번에 두 개를 반환 가능
print(total_sales_per_fruit)

most_sold_fruit = np.argmax(total_sales_per_fruit)
print(most_sold_fruit)


[4340 3515 3260]
0
[4340 3515 3260]
0


In [106]:
#4. 각 지점에서 판매량이 150개 이상인 데이터를 추출하고 그에 해당하는 지점과 과일을 출력하세요.
# print(sales_data[sales_data > 150])

# print(sales_data[0][0][0])
# for i in range(5):
#     for j in range(3):
#         for k in range(6):
#             if sales_data[i][j][k] >= 150:
#                 print(f"{i}지점 {j+1}번 과일은 {sales_data[i][j][k]}개 입니다.")

# T
high_sales_data = sales_data[sales_data >= 150]
print(high_sales_data)

high_sales_idx = np.where(sales_data >= 150) # 배열이 순서대로 0번 1번 2번 배열로 들어감
print(high_sales_idx)

for i in range(len(high_sales_idx[0])):
    spot = high_sales_idx[0][i] + 1
    fruit = high_sales_idx[1][i]
    fruit = ["사과", "바나나", "오렌지"][fruit]     # ndarray를 찾을 때는 별도로 명칭을 넣을 수 없어서 따로 명칭을 추가해줘야한다.
    month = high_sales_idx[2][i] + 1
    print(f"{spot}지점 {fruit}, {month}월")

[150 200 230 180 210 170 190 160 180 160 150 160 180 170 190 150 160 150
 170 160 180]
(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3]), array([0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0]), array([1, 2, 3, 4, 5, 2, 3, 4, 5, 2, 5, 2, 3, 4, 5, 3, 5, 2, 3, 4, 5]))
1지점 사과, 2월
1지점 사과, 3월
1지점 사과, 4월
1지점 사과, 5월
1지점 사과, 6월
1지점 바나나, 3월
1지점 바나나, 4월
1지점 바나나, 5월
1지점 바나나, 6월
1지점 오렌지, 3월
1지점 오렌지, 6월
3지점 사과, 3월
3지점 사과, 4월
3지점 사과, 5월
3지점 사과, 6월
3지점 바나나, 4월
3지점 바나나, 6월
4지점 사과, 3월
4지점 사과, 4월
4지점 사과, 5월
4지점 사과, 6월
